---
- name: Resync configs
  hosts: service_hosts
  gather_facts: false
  tasks:
    - name: sync repo
      ansible.builtin.git:
        repo: "{{ config_repo_url }}"
        dest: "{{ config_repo_path }}"
        version: "{{ config_repo_version }}"
        key_file: "~/.ssh/config_repo_key"
        update: true
        force: true
        accept_hostkey: true

- name: Local services up
  hosts: local-srvc
  gather_facts: false
  tasks:
    - name: make up
      community.general.make:
        chdir: "{{ config_repo_path }}/{{ inventory_hostname }}"
        target: up

